services:
  detection:
    build:
      context: "src/perceptree"
      dockerfile: "dockerfile.perceptree"
    ports:
      - "8000:8000"
      - "6379:6379"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    # runtime: nvidia  # For GPU support
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

