name: timbertrack
channels:
    - defaults
    - conda-forge
    - pytorch
    - anaconda
    - nvidia
 
dependencies:
    - python=3.8
    - redis
    - numpy
    - pydantic
    - fastapi
    - uvicorn
    - opencv
    - pandas
    - torch
    - torchvision
    - pip:
        - jsonpickle
        - sse-starlette
        - 'detectron2 @ git+https://github.com/facebookresearch/detectron2.git'
    